# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FBVaD-HNwsFK2ZFqJBSAbaR9w82EWZaq
"""

import tensorflow as tf

model=tf.keras.models.Sequential([
    tf.keras.layers.Input((42,)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(40,activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(30,activation='relu'),
    tf.keras.layers.Dense(5,activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
    )

model.fit(
    X_train,
    Y_train,
    epochs=100,
    batch_size=64,
    validation_data=(X_val,Y_val)
)